### ISSUE TITLE
Unable to locate "module.xml"

### ISSUE THREAD

**Issue by friendscottn** [DrewML/baler#10]
Hey there,
Baler hit the following error on the mirasvit elastic search ultimate module:
```
Error: Unable to locate "module.xml" for the module at path "vendor/mirasvit/module-search-elastic-ultimate"
    at findRealModuleRoot (/Users/scottfriend/Sites/baler/src/magentoFS.ts:241:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at getModuleConfig (/Users/scottfriend/Sites/baler/src/magentoFS.ts:204:28)
    at async Promise.all (index 154)
    at getComposerComponents (/Users/scottfriend/Sites/baler/src/magentoFS.ts:332:18)
    at async Promise.all (index 0)
    at Object.getComponents (/Users/scottfriend/Sites/baler/src/magentoFS.ts:62:37)
    at async Promise.all (index 1)
    at Object.collectStoreData (/Users/scottfriend/Sites/baler/src/collectStoreData.ts:15:58)
    at Object.run (/Users/scottfriend/Sites/baler/src/cli.ts:20:19)
```
This composer module doesn't actually contain a Magento Module. It's just a shell of a module to pull in other separate actual Magento modules via the compser.json it contains. Kinda goofy, but I think it allows Mirasvit to sell a module that is really just a bundle of other modules.

The contents of the directory are:
- vendor/mirasvit/module-search-elastic-ultimate
  - CHANGELOG.md
  - composer.json

Maybe baler could just skip over modules that don't contain a valid module.xml file?

**Comment by DrewML** [comment]
Thanks for the great bug report @friendscottn! The dir listing for the module is _extremely_ helpful.

I'm going to take a guess that `mirasvit/module-search-elastic-ultimate/composer.json` has the `type` set to `magento2-module`? 

Right now, we make an assumption that anything of type `magento2-module` will have a `module.xml`:

https://github.com/DrewML/baler/blob/b4c4503318bf53c791b1bc997cc967837bcff273/src/magentoFS.ts#L333-L336

TBH my understanding of the composer/php side of things is fairly naive still, but I assumed that if something is labeled as `magento2-module`, it must have the module requirements (`module.xml`, `registration.php`, etc).

Do you know if this is a fairly common pattern? I would have expected a [metapackage](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/prepare/dev-modtypes.html) to be used for a bundle of modules. BUT, if there are enough modules in the wild that do this, we probably should support it.

**Comment by friendscottn** [comment]
Thanks @DrewML 
You are correct. The composer.json looks like this:
```
{
    "name": "mirasvit/module-search-elastic-ultimate",
    "description": "Elastic Search Ultimate",
    "require": {
        "mirasvit/module-search-elastic": "1.2.*",
        "mirasvit/module-search-autocomplete": "1.1.*",
        "mirasvit/module-misspell": "1.0.*",
        "mirasvit/module-search-landing": "1.0.*",
        "mirasvit/module-search-report": "1.0.*"
    },
    "type": "magento2-module",
    "version": "1.1.0",
    "license": [
        "proprietary"
    ]
}
```

**Comment by Vinai** [comment]
> I'll get this fixed. If a module does not have a registration.php in autoload that registers the module, we can safely skip it.

This will soon no longer be true. Current plans are to make the `registration.php` optional and discouraged for modules that are installed with composer.
https://github.com/magento/architecture/pull/162 (long thread warning)

**Comment by DrewML** [comment]
Work in #12 is done, which I believe (🤞) would fix this issue. I'll wait to hear confirmation

**Comment by friendscottn** [comment]
Yep. Got it.
