### ISSUE TITLE
Support for monorepo modules or disabling modules

### ISSUE THREAD

**Issue by jcodo** [DrewML/baler#14]
I'm aware that this project is still in its infancy but I'm pleased to see it developing so well!

When running baler in the root of my Magento 2 store, I get an immediate error

> Error: ENOENT: no such file or directory, open

complaining that '/etc/module.xml' does not exist in one of our third-party modules in the vendor directory. This is true because this vendor has decided to place their 2 Magento 2 modules in the same composer package. Therefore the path to each should be 'vendor/vendorname/modulename/src/module1/etc/module.xml' etc.

If this is a complicated issue to solve then some documented way to disable some modules from being bundled would also be great.

**Comment by Vinai** [comment]
Related Issues:
* https://github.com/DrewML/baler/issues/11
* https://github.com/DrewML/baler/issues/8

**Comment by DrewML** [comment]
Thanks for the report @jcodo, and thanks @Vinai for beating me to it 😄 

This should have been fixed in c0c3bac9. What's the latest commit you have locally?
