### ISSUE TITLE
Error: ENOTDIR: not a directory, scandir ' .. /app/code/.DS_Store'

### ISSUE THREAD

**Issue by EirikSl** [DrewML/baler#5]
Then I try to run baler in my root Magento project it stuck with such error:
Error: ENOTDIR: not a directory, scandir ' .. /app/code/.DS_Store'

Yes, I use Mac. To reproduce on Linux try to create the same dir with "."

**Comment by Vinai** [comment]
The code needs to be fixed to not only expect directories in `app/code`, but maybe the following workaround is helpful. If you already know please ignore.

The `.DS_Store` file is created whenever a directory is opened in the Finder.
As a workaround, delete the `.DS_Store files.
You can do that by running the following command from the Magento base directory:

`find app/code -name .DS_Store -exec rm {} \;`

This will delete all `.DS_Store` files within `app/code`.

**Comment by DrewML** [comment]
Thanks for the report, Victor. This is fixed in 40c7b81dcd6 in `master`.

Re: your next bug, if you want a second pair of eyes, feel free to run `BALER_LOG_LEVEL=debug baler` and post the results in a new issue.
