### ISSUE TITLE
Baler finding wrong dirs for files ("Error: ENOENT: no such file or directory")

### ISSUE THREAD

**Issue by jessetaverne** [DrewML/baler#8]
> Unsure whether this is or isn't a Baler issue, or something modulemakers could be doing wrong.

When running 'baler/bin/baler' from the root i get the following message:
```Error: ENOENT: no such file or directory, open [domain]/vendor/mirasvit/module-helpdesk/etc/module.xml```

> My assumption here is that baler is spitting through modules to find dependencies and possible JS files to bundle?

This is actually correct though, the location it should be looking for is `vendor/mirasvit/module-helpdesk/src/Helpdesk/etc/module.xml`. I believe the module maps these locations through composer.json: 

![image](https://user-images.githubusercontent.com/4201466/63591149-31ae5200-c5ae-11e9-920c-0a09beb841a6.png)

It looks like there's an assumption about where baler should find vendor files, based on the generated files? This assumption then doesn't take into account that modulemakers might map their modules in a different way.

I could be totally off-base here, but hope this helps make baler the tool we'll all be using in a month (or two ;))

**Comment by DrewML** [comment]
Thanks for the thorough bug report, Jesse! You're 100% correct about the root cause. We're making an (apparently poor) assumption that `etc/` and `view/` can be found in the root dir of the composer package. I'll get a fix in today

**Comment by jessetaverne** [comment]
@DrewML This is fixed in so far that my Mirasvit modules are reinstalled and baler doesn't find issues with them!
