### ISSUE TITLE
Cannot read property 'area' of undefined

### ISSUE THREAD

**Issue by jessetaverne** [DrewML/baler#9]
After uninstalling the conflicting module for testing purposes (see issue #8) and then running baler again I got the following typeError:

```bash> baler/bin/baler
TypeError: Cannot read property 'area' of undefined
    at Object.bundleThemes ([magento-root]/baler/src/index.ts:24:19)
    at Object.run ([magento-root]/baler/src/cli.ts:23:27)
```

This leads to the following code:

```
export async function bundleThemes(
    magentoRoot: string,
    store: StoreData,
): Promise<BundleResult[]> {
    const { components, deployedThemes } = store;

    const pendingBundleResults: ReturnType<typeof bundleSingleTheme>[] = [];
    for (const themeID of deployedThemes) {
        const theme = components.themes[themeID]; //<< LEADS TO HERE 2/2
        if (theme.area !== 'frontend' || theme.themeID === 'Magento/blank') {  //<< HERE 1/2
            continue;
        }
```

I'm not unsure of how to debug this but it seems strange that the theme val is undefined, unless the components.themes array doesn't match IDs with IDs in deployed Themes?

Also: I'm running this on a dev-server - should that even work, or do i need to test on production mode?

**Comment by DrewML** [comment]
> I'm running this on a dev-server - should that even work, or do i need to test on production mode?

I _believe_ any mode should be fine, but I will say that I've primarily been testing in production mode, so YMMV.

Quick way for us to debug this.

1. Get access to a shell on the machine `baler` is running on
2. Run `node` to get into the REPL
3. Paste and run the following code:
```js
// Note: Replace `./dist/collectStore` with the full path to
// wherever the installed package is on disk. We're just reaching
// in and grabbing a module to see what data we've been working with
require('./dist/collectStoreData')
	.collectStoreData('/Users/andrewlevine/sites/baler')
	.then(v => JSON.stringify(v, null, 2))
	.then(console.log);
```
4. Send me the results :)

**Comment by DrewML** [comment]
I _think_ this is fixed with https://github.com/DrewML/baler/commit/3a33551327edbbc315e8a4fb7fe0924694ca8c75 and https://github.com/DrewML/baler/commit/7d814cfe17041af1e0940202d4887c3487efabc3. We're now getting the `themeID` from the module's `registration.php`, rather than attempting to infer it from the composer package's name, which isn't a strict convention.

@jessetaverne Please verify when you have time :)

**Comment by jessetaverne** [comment]
@DrewML 

I think we got a little bit further:

### Before disabling minification:
Running `baler/bin/baler` gets me to the following output
```
[
  {
    "themeID": "Experius/whitelabel",
    "success": false,
    "error": {}
  },
  {
    "themeID": "Magento/luma",
    "success": false,
    "error": {}
  },
  {
    "themeID": "PowerComponents/default",
    "success": false,
    "error": {}
  }
]
undefined
```

#### On the themes:
When I compare this to my deployed themes these results seem correct:

- Luma: has been deployed (but isn't acutally used, so that's on me), installed by composer
- Experius/whitelabel is our parent theme, installed by composer
- Powercomponents/default is the main theme that we want this to work with, installed in app/design/frontend

#### On the success: false / error: {}
From what I can tell:
- the script works until `const { requireConfig, rawRequireConfig } = await requireConfig_1.getRequireConfigFromDir(firstLocaleRoot);` in dist/optimizeThemes.js (r.50).
- this calls getRequireConfigFromDir in dist/requireConfig.js r.102, which tries to find requirejs-config.js. 

**The issue: minification**
The code doesn't account for minimized JS: requirejs-config.min.js! 
I just found out I had bundling enabled due to our production-mode deploy script i ran.

**No error?**
The error that's supposed to show (`Failed reading or evaluating RequireJS config at path "/home/user/domain/pub/static/frontend/PowerComponents/default/de_DE"`) there isn't thrown back to me in any way (I'm testing by running baler/bin/baler in MacOS' terminal and throwing console.log()s around the JS files, is there a more efficient way for this script?)

### After disabling JS minification (and merging):
- requirejs-config.js is found, but the same function still does not complete :(
- The raw content seems to be correct (did not test output, only whether or not there was any that looked like the file).
- I get the same output though (themeID: [themeID], success: false, error: {})
- I then followed a trail of console.logs, which led me to the `evaluateRawConfig` function, which works until `vm_1.default.runInContext(rawConfig, sandbox);` is called. This seems to throw an error, because any console.log afterwards doesn't show up in my terminal. From there it's a little too deep for me to say anything about why/how. Hopefully this helps you get further though.

### **Bonus content**
I have been testing `async function optimizeTheme(magentoRoot, store, theme, minifier)` a little bit to see what it would spit out at me.
Logging `magentoRoot` and `store` seem to give correct results, though `store` is too big to test for me right now.
When i log the `theme` var (see below for log) i get the correct info, except (i think) for pathFromStoreRoot. The themes installed with composer show a path from server root instead of from Store Root (including /home/user/domain/... etc). Now that i type this, it might not be an issue, unless they're appended to another string (eg. magentoRoot). Just something to be aware of if you weren't already.
The local theme (in app/design) has pathFromStoreRoot starting with app/design so that does seem correct.

```
{ name: 'whitelabel',
  vendor: 'Experius',
  themeID: 'Experius/whitelabel',
  area: 'frontend',
  parentID: '',
  pathFromStoreRoot:
   '/home/user/domain/vendor/experius/theme-frontend-base-sass' }
{ name: 'luma',
  vendor: 'Magento',
  themeID: 'Magento/luma',
  area: 'frontend',
  parentID: 'Magento/blank',
  pathFromStoreRoot:
   '/home/user/domain/vendor/magento/theme-frontend-luma' }
{ name: 'default',
  vendor: 'PowerComponents',
  themeID: 'PowerComponents/default',
  area: 'frontend',
  parentID: 'Experius/whitelabel',
  pathFromStoreRoot: 'app/design/frontend/PowerComponents/default' }
```
Also: not sure if these theme _names_ should be unique or more identifiable, but right now PowerComponents/default has "default" as name, which seems like something that might conflict sooner rather than later, if that's something they're ID'd by too.

**Comment by DrewML** [comment]
Wow @jessetaverne! Thanks for such a thorough write-up. Hopefully I'm able to address everything


> The code doesn't account for minimized JS: requirejs-config.min.js!

Sorry you had to figure this one out the hard way 😞. I have a requirement listed for the Magento module to disable minification when enabled. See https://github.com/DrewML/baler/issues/1

> (I'm testing by running baler/bin/baler in MacOS' terminal and throwing console.log()s around the JS files, is there a more efficient way for this script?

You can run with `BALER_LOG_LEVEL=debug`, but it's only wired up in certain places so far, so may not have the info you need.

If you want to walk through the code with a debugger, there is a [section in the readme](https://github.com/DrewML/baler#nodejs-debugger) for it!

> When i log the theme var (see below for log) i get the correct info, except (i think) for pathFromStoreRoot. The themes installed with composer show a path from server root instead of from Store Root (including /home/user/domain/... etc). Now that i type this, it might not be an issue, unless they're appended to another string (eg. magentoRoot). Just something to be aware of if you weren't already.

You're thinking was right here - that was 100% a bug that crept in during another refactor of some path handling. In #12 we switched to tracking absolute paths, so this should no longer be an issue.

> Also: not sure if these theme names should be unique or more identifiable, but right now PowerComponents/default has "default" as name, which seems like something that might conflict sooner rather than later, if that's something they're ID'd by too.

TBH I don't know why I still have `name` as a property in the `Theme` type - pretty sure it's not used anywhere, and we can always derive it later by splitting the `themeID`.

**Comment by DrewML** [comment]
Regarding what it seems is the actual issue at this point, seems like something is up with [`evaluateRawConfig`](https://github.com/DrewML/baler/blob/c0c3bac9ff6801c984e41b3e4964255edc4107c4/src/requireConfig.ts#L28-L52).

For context, the bundler needs all your `map`, `paths`, and `deps` entries. Because Magento concatenates all the separate `requirejs-config.js` files into a file with multiple function calls, I need to execute it so I can get a single, merged object back (RequireJS has special config merging rules we want to respect).

My guess is you probably have some executable code inside the file that isn't working in the sandbox. Can you send me the entirety of one of the merged `requirejs-config.js` files in `pub/static/frontend/Powercomponents/default`?

**Comment by jessetaverne** [comment]
Ah wow, shouldve seen that section on debugging but somehow missed it.
Won't be able to spend any more time on this until a week or two after this, but I sent you the requirejs-config file privately on Twitter. Hopefully it gets you further ahead.
I look forward to seeing the progress in a week or two! (no pressure ;))

**Comment by DrewML** [comment]
Thanks @jessetaverne! Was able to get a failing test going with the supplied config:

![image](https://user-images.githubusercontent.com/5233399/64031365-dd572500-cb0d-11e9-9e67-e5d8e036552d.png)

Enjoy your vacation 😃

**Comment by DrewML** [comment]
Fixed in https://github.com/DrewML/baler/commit/ecb0aefaf24b1f9831d06875f97fe231435dae86
